[CmdletBinding()]
param(
  [ValidateSet('Plan', 'Apply', 'Verify')]
  [string]$Action = 'Plan',
  [Parameter(Mandatory = $true)]
  [string]$ControllerRoot,
  [string]$ControllerName = 'Multi-Project Control Center',
  [string[]]$BusinessProjectRoots = @()
)

Set-StrictMode -Version 2
$ErrorActionPreference = 'Stop'
$utf8 = New-Object Text.UTF8Encoding($false, $true)
$skillRoot = Split-Path -Parent $PSScriptRoot
$templateRoot = Join-Path $skillRoot 'templates\controller'

$managedFiles = @('.dsh-controller.json', '.chain-store.json', '.gitignore', 'AGENTS.md', 'TASKS.md', 'docs\cross-project-contracts.md', 'tools\control-state.ps1', 'tools\chain-store.ps1', 'memory\MEMORY.md')
$managedDirs = @('docs', 'tools', 'memory', 'state', 'state\active', 'state\archive')
$allowedRootItems = @('.git', '.dsh-controller.json', '.chain-store.json', '.gitignore', 'AGENTS.md', 'TASKS.md', 'docs', 'tools', 'memory', 'state')

function Get-Hash {
  param([byte[]]$Bytes)
  $sha = [Security.Cryptography.SHA256]::Create()
  try { return ([BitConverter]::ToString($sha.ComputeHash($Bytes))).Replace('-', '').ToLowerInvariant() }
  finally { $sha.Dispose() }
}

function Write-Result {
  param([string]$Status, [AllowNull()][object]$Fields, [int]$ExitCode)
  $obj = New-Object PSObject
  $obj | Add-Member -NotePropertyName 'schemaVersion' -NotePropertyValue 1
  $obj | Add-Member -NotePropertyName 'action' -NotePropertyValue $Action
  $obj | Add-Member -NotePropertyName 'status' -NotePropertyValue $Status
  if ($null -ne $Fields) {
    if ($Fields -is [Collections.IDictionary]) {
      foreach ($entry in $Fields.GetEnumerator()) {
        $obj | Add-Member -NotePropertyName ([string]$entry.Key) -NotePropertyValue $entry.Value
      }
    }
    else {
      foreach ($prop in @($Fields.PSObject.Properties)) {
        $obj | Add-Member -NotePropertyName ([string]$prop.Name) -NotePropertyValue $prop.Value
      }
    }
  }
  $obj | ConvertTo-Json -Depth 12 -Compress
  exit $ExitCode
}

function Test-LosslessPath {
  param([string]$Path)
  if ([string]::IsNullOrWhiteSpace($Path) -or $Path -notmatch '^[A-Za-z]:\\' -or $Path.Substring(2).Contains(':') -or $Path.Contains('/')) { return $false }
  try { $normalized = [IO.Path]::GetFullPath($Path).TrimEnd('\') } catch { return $false }
  if ($normalized -ieq [IO.Path]::GetPathRoot($normalized).TrimEnd('\')) { return $false }
  $leaf = [IO.Path]::GetFileName($normalized)
  if ([string]::IsNullOrWhiteSpace($leaf) -or $leaf -match '[<>:"/\\|?*\x00-\x1f]' -or
      $leaf -match '^(?i:con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\..*)?$' -or $leaf.EndsWith('.') -or $leaf.EndsWith(' ')) { return $false }
  return $true
}

function Test-Overlap {
  param([string]$Root, [string[]]$BusinessRoots)
  $rootPrefix = $Root.TrimEnd('\') + '\'
  foreach ($business in $BusinessRoots) {
    if ([string]::IsNullOrWhiteSpace($business) -or $business -notmatch '^[A-Za-z]:\\') { return $true }
    try { $b = [IO.Path]::GetFullPath($business).TrimEnd('\') } catch { return $true }
    $bPrefix = $b + '\'
    if ($Root.Equals($b, [StringComparison]::OrdinalIgnoreCase) -or
        $Root.StartsWith($bPrefix, [StringComparison]::OrdinalIgnoreCase) -or
        $b.StartsWith($rootPrefix, [StringComparison]::OrdinalIgnoreCase)) { return $true }
  }
  return $false
}

function Get-RenderedManifestBytes {
  $encodedName = $ControllerName | ConvertTo-Json -Compress
  $templateText = [IO.File]::ReadAllText((Join-Path $templateRoot '.dsh-controller.json'), $utf8)
  if ($templateText -match '\x00' -or -not $templateText.Contains('__CONTROLLER_NAME_JSON__')) { throw 'invalid-manifest-template' }
  $rendered = $templateText.Replace('__CONTROLLER_NAME_JSON__', $encodedName)
  return $utf8.GetBytes($rendered.TrimEnd() + "`n")
}

function Get-MemoryTemplateBytes {
  $text = @'
# Controller Memory (bounded)

Capped at 200 lines / 25 KiB. Only cross-project facts belong here:

- Frozen contracts (pointer to docs/cross-project-contracts.md)
- Dispatch queue summary and model-tier evidence
- Deterministic failures and the next allowed strategy per problem signature

Per-project detail lives in each project entry agent. Never dump task logs here.
'@
  return $utf8.GetBytes($text + "`n")
}

function Get-TasksTemplateBytes {
  $text = @'
# TASKS (bounded human dashboard)

| Dispatch | Repo | Phase | Status | Updated |
| --- | --- | --- | --- | --- |

(Regenerated by the controller agent from manifest queues and CHAIN index.
Never hand-edit; never treat as authoritative.)
'@
  return $utf8.GetBytes($text + "`n")
}

function Invoke-Adapter {
  param([string]$AdapterName, [string[]]$Arguments)
  $adapter = Join-Path $ControllerRoot ('tools\' + $AdapterName)
  $output = & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $adapter @Arguments 2>$null
  $exitCode = $LASTEXITCODE
  try { $parsed = (($output | ForEach-Object { [string]$_ }) -join [Environment]::NewLine) | ConvertFrom-Json -ErrorAction Stop }
  catch { return [pscustomobject]@{ ExitCode=$exitCode; Result=$null } }
  return [pscustomobject]@{ ExitCode=$exitCode; Result=$parsed }
}

function Get-Inventory {
  param([bool]$RequireComplete)
  $missing = New-Object Collections.Generic.List[string]
  if (-not (Test-Path -LiteralPath $ControllerRoot -PathType Container)) {
    if ($RequireComplete) { return [pscustomobject]@{ Ready=$false; Reason='controller-not-initialized'; Missing=(@($managedDirs) + @($managedFiles) + @('state\index.json')); Unknown=@() } }
    foreach ($path in @($managedDirs) + @($managedFiles) + @('state\index.json')) { $missing.Add($path) }
    return [pscustomobject]@{ Ready=$true; Missing=$missing.ToArray(); Unknown=@() }
  }
  $unknown = New-Object Collections.Generic.List[string]
  foreach ($item in @(Get-ChildItem -Force -LiteralPath $ControllerRoot)) {
    if ($allowedRootItems -cnotcontains $item.Name) { $unknown.Add($item.Name) }
  }
  foreach ($path in @($managedDirs) + @($managedFiles) + @('state\index.json')) {
    if (-not (Test-Path -LiteralPath (Join-Path $ControllerRoot $path))) { $missing.Add($path) }
  }
  if ($RequireComplete -and ($missing.Count -gt 0 -or $unknown.Count -gt 0)) {
    return [pscustomobject]@{ Ready=$false; Reason='controller-filesystem-conflict'; Missing=$missing.ToArray(); Unknown=$unknown.ToArray() }
  }
  return [pscustomobject]@{ Ready=$true; Missing=$missing.ToArray(); Unknown=$unknown.ToArray() }
}

if ([string]::IsNullOrWhiteSpace($ControllerName) -or $ControllerName.Length -gt 80 -or $ControllerName -match '[\x00-\x1f\x7f/\\]') {
  Write-Result 'invalid' ([ordered]@{ reasonCode='invalid-controller-input'; nextAction='Use a non-blank controller name of at most 80 characters without control characters or slashes.' }) 2
}
if (-not (Test-LosslessPath $ControllerRoot)) {
  Write-Result 'invalid' ([ordered]@{ reasonCode='controller-root-unsupported'; nextAction='Use an absolute local-drive child directory path without dot segments or reserved names.' }) 2
}
$normalized = [IO.Path]::GetFullPath($ControllerRoot).TrimEnd('\')
$parent = Split-Path -Parent $normalized
if (-not (Test-Path -LiteralPath $parent -PathType Container)) {
  Write-Result 'blocked' ([ordered]@{ reasonCode='controller-root-unsupported'; nextAction='Create the parent directory, then rerun.' }) 1
}
if (Test-Overlap -Root $normalized -BusinessRoots @($BusinessProjectRoots)) {
  Write-Result 'conflict' ([ordered]@{ reasonCode='controller-root-overlap'; nextAction='Choose a controller root outside every business project root.' }) 1
}

$manifestBytes = Get-RenderedManifestBytes
$resultHash = Get-Hash $manifestBytes
$inventory = Get-Inventory -RequireComplete ($Action -ceq 'Verify')

if ($Action -ceq 'Verify') {
  if (-not $inventory.Ready) {
    Write-Result 'conflict' ([ordered]@{ reasonCode=$inventory.Reason; missing=$inventory.Missing; unknown=$inventory.Unknown }) 1
  }
  $state = Invoke-Adapter 'control-state.ps1' @('-Action', 'Read', '-ControllerRoot', $normalized)
  if ($state.ExitCode -ne 0 -or $null -eq $state.Result -or $state.Result.status -cne 'verified' -or [string]$state.Result.data.controllerName -cne $ControllerName) {
    Write-Result 'conflict' ([ordered]@{ reasonCode='controller-filesystem-conflict'; nextAction='Review the manifest and its state adapter output before retrying.' }) 1
  }
  $store = Invoke-Adapter 'chain-store.ps1' @('-Action', 'Verify', '-ControllerRoot', $normalized)
  if ($store.ExitCode -ne 0 -or $null -eq $store.Result -or $store.Result.status -cne 'verified') {
    Write-Result 'conflict' ([ordered]@{ reasonCode='controller-filesystem-conflict'; nextAction='Run the chain-store verifier and rebuild only after inspecting its exact failure.' }) 1
  }
  Write-Result 'verified' ([ordered]@{ controllerRoot=$normalized; resultManifestHash=$state.Result.currentHash }) 0
}

if ($inventory.Unknown.Count -gt 0) {
  Write-Result 'conflict' ([ordered]@{ reasonCode='controller-filesystem-conflict'; unknownItems=@($inventory.Unknown); nextAction='Remove or relocate the unknown inventory items, then rerun.' }) 1
}

$planned = @($inventory.Missing)
if ($Action -ceq 'Plan') {
  Write-Result 'planned' ([ordered]@{ controllerRoot=$normalized; plannedCreates=@($planned); currentManifestHash=$null; resultManifestHash=$resultHash; changed=($planned.Count -gt 0); nextAction='Run Apply with the same controller root and name.' }) 0
}

# --- Apply ----------------------------------------------------------------
try {
  [IO.Directory]::CreateDirectory($normalized) | Out-Null
  foreach ($dir in $managedDirs) {
    $path = Join-Path $normalized $dir
    if (-not (Test-Path -LiteralPath $path)) { [IO.Directory]::CreateDirectory($path) | Out-Null }
  }
  function Write-NewFile {
    param([string]$Relative, [byte[]]$Bytes)
    $path = Join-Path $normalized $Relative
    if (Test-Path -LiteralPath $path -PathType Leaf) { return }
    [IO.Directory]::CreateDirectory((Split-Path -Parent $path)) | Out-Null
    $stream = New-Object IO.FileStream($path, [IO.FileMode]::CreateNew, [IO.FileAccess]::Write, [IO.FileShare]::None)
    try { $stream.Write($Bytes, 0, $Bytes.Length); $stream.Flush() }
    finally { $stream.Dispose() }
  }
  Write-NewFile '.dsh-controller.json' $manifestBytes
  foreach ($template in @('.chain-store.json', '.gitignore', 'AGENTS.md', 'docs\cross-project-contracts.md', 'tools\control-state.ps1', 'tools\chain-store.ps1')) {
    Write-NewFile $template ([IO.File]::ReadAllBytes((Join-Path $templateRoot $template)))
  }
  Write-NewFile 'memory\MEMORY.md' (Get-MemoryTemplateBytes)
  Write-NewFile 'TASKS.md' (Get-TasksTemplateBytes)

  $store = Invoke-Adapter 'chain-store.ps1' @('-Action', 'Rebuild', '-ControllerRoot', $normalized)
  if ($store.ExitCode -ne 0 -or $null -eq $store.Result -or $store.Result.status -cne 'applied') { throw 'chain-store rebuild failed' }
  $state = Invoke-Adapter 'control-state.ps1' @('-Action', 'Read', '-ControllerRoot', $normalized)
  if ($state.ExitCode -ne 0 -or $null -eq $state.Result -or $state.Result.status -cne 'verified') { throw 'manifest readback failed' }
  if ([string]$state.Result.data.controllerName -cne $ControllerName -or $state.Result.currentHash -cne $resultHash) { throw 'manifest readback mismatch' }
  Write-Result 'applied' ([ordered]@{ controllerRoot=$normalized; plannedCreates=@($planned); resultManifestHash=$state.Result.currentHash; changed=($planned.Count -gt 0); nextAction='The controller scaffold is ready; register project bindings and create the controller agent next.' }) 0
}
catch {
  Write-Result 'blocked' ([ordered]@{ reasonCode='controller-io-failure'; detail=$_.Exception.Message; nextAction='Inspect the controller root for a concurrent change or I/O failure, then rerun Plan.' }) 1
}
