[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)]
  [string]$ControllerRoot
)
# Regenerates TASKS.md (the bounded human dashboard) from the controller manifest.
# Read-only toward state; writes only TASKS.md. Run from the skill's scripts dir.
$ErrorActionPreference = 'Stop'

$root = [IO.Path]::GetFullPath($ControllerRoot)
$control = Join-Path $root 'tools\control-state.ps1'
if (-not (Test-Path -LiteralPath $control -PathType Leaf)) {
  Write-Error "control-state.ps1 not found under $root"
  exit 2
}
$read = & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $control -Action Read -ControllerRoot $root | ConvertFrom-Json
if ($read.status -ne 'verified') {
  Write-Error "manifest not verified (status: $($read.status))"
  exit 2
}
$m = $read.data

$rows = New-Object Collections.Generic.List[object]
foreach ($q in @($m.dispatchQueues)) {
  if ($null -ne $q.active) {
    $rows.Add([pscustomobject]@{ Dispatch = [string]$q.active.dispatchId; Repo = [string]$q.repoId; Phase = [string]$q.active.phase; Status = 'active'; Updated = [string]$q.active.startedAtUtc })
  }
  foreach ($p in @($q.pending)) {
    $status = 'pending'
    if ([string]$p.accessMode -ceq 'external-write') {
      $status = if ($null -ne $p.authorization -and [string]$p.authorization.status -ceq 'granted') { 'authorized' } else { 'auth-pending' }
    }
    if ($p.PSObject.Properties.Name -contains 'dependencies' -and $null -ne $p.dependencies) { $status += ' (deps)' }
    $rows.Add([pscustomobject]@{ Dispatch = [string]$p.dispatchId; Repo = [string]$q.repoId; Phase = 'pending'; Status = $status; Updated = [string]$p.enqueuedAtUtc })
  }
  if ($null -ne $q.lastTerminal) {
    $rows.Add([pscustomobject]@{ Dispatch = [string]$q.lastTerminal.dispatchId; Repo = [string]$q.repoId; Phase = 'terminal'; Status = [string]$q.lastTerminal.resultState; Updated = [string]$q.lastTerminal.finishedAtUtc })
  }
}

$activeChains = 0
$recentChains = 0
$idxPath = Join-Path $root 'state\index.json'
if (Test-Path -LiteralPath $idxPath -PathType Leaf) {
  try {
    $idx = Get-Content -LiteralPath $idxPath -Raw | ConvertFrom-Json
    $activeChains = @($idx.activeChains).Count
    $recentChains = @($idx.recentTerminal).Count
  }
  catch { }
}

$sb = New-Object Text.StringBuilder
[void]$sb.AppendLine('# TASKS (bounded human dashboard)')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('(Generated by `scripts/rebuild-dashboard.ps1` from the controller manifest.')
[void]$sb.AppendLine('Never hand-edit; never treat as authoritative state.)')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('| Dispatch | Repo | Phase | Status | Updated |')
[void]$sb.AppendLine('| --- | --- | --- | --- | --- |')
foreach ($r in $rows) {
  [void]$sb.AppendLine(('| {0} | {1} | {2} | {3} | {4} |' -f $r.Dispatch, $r.Repo, $r.Phase, $r.Status, $r.Updated))
}
[void]$sb.AppendLine('')
[void]$sb.AppendLine(('Active CHAINs: {0}; recent terminal CHAINs: {1}.' -f $activeChains, $recentChains))

$out = Join-Path $root 'TASKS.md'
[IO.File]::WriteAllText($out, $sb.ToString(), [Text.UTF8Encoding]::new($false))
Write-Output ("TASKS.md regenerated: {0} rows" -f $rows.Count)
